import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { client } from "@/sanity/lib/client";
import { settingsQuery } from "@/sanity/lib/queries";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const data = await client.fetch(settingsQuery);
  // console.log(data.navigation)
  return (
      <div className={inter.className}>
          <Navbar image={data.logo} navItems={data.navigation}/>
          {children}
          <Footer image={data.logo} />
      </div>
  );
}
